
server:
  port: 8003

spring:
  application:
    name: eureka-client-test

eureka:
  client:
    # 集群所属区域
    region: sdn-region
    prefer-same-zone-eureka: true
    # 是否开启心跳
    #healthcheck:
    #  enabled: true

  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}@${release.version}
    # 续约更新时间间隔 (默认30秒)
    lease-expiration-duration-in-seconds: 15
    # 续约到期事件 (默认90秒)
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    metadata-map:
      # 所在分区，如:HD、HB、HN、Gi、CNLAB
      zone: HN