
server:
  port: 80

springdoc:
  # 不导入的接口
  paths-to-exclude: /error
  swagger-ui:
    path: /webui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      # actuator endpoint 的 base path，默认为/actuator/
      base-path: /