
release:
  version: 1.3.2

server:
  port: 8081

spring:
  application:
    name: gateway-test
  # spring cloud配置
  cloud:
    inetutils:
      ignored-interfaces:
        - lo
      preferred-networks:
        - 172.*
    gateway:
      # 使能基于服务注册中心路由的功能，会创建一个相应的route
      discovery:
        locator:
          enabled: true
      routes:
        - id: eureka_route #路由的ID
          uri: lb://eureka-test #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/eureka-test/**
          filters:
            - RewritePath=/eureka-test(?<segment>/?.*), $\{segment}
            - GatewayTest=true
            - name: Retry
              args:
                retries: 3
                series:
                  - SERVER_ERROR
                statuses:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
                methods:
                  - GET
                exceptions:
                  - java.io.IOException
                  - java.util.concurrent.TimeoutException
        - id: topo-service #路由的ID
          uri: lb://topo-service #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/topo-service/**
          filters:
            - RewritePath=/topo-service(?<segment>/?.*), $\{segment}
            - GatewayTest=true


# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: info

eureka:
  client:
    service-url:
      defaultZone: http://10.114.37.44:8002/eureka/,http://10.162.24.155:8002/eureka/
    # 集群所属区域
    region: sdn-region
    prefer-same-zone-eureka: true
    # 是否开启心跳
    healthcheck:
      enabled: true

  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}@${release.version}
    # 续约更新时间间隔 (默认30秒)
    lease-expiration-duration-in-seconds: 15
    # 续约到期事件 (默认90秒)
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    metadata-map:
      # 所在分区，如:HD、HB、HN、Gi、CNLAB
      zone: HN

# 开通安全认证
management:
  security:
    enabled: false
    roles: USER
  info:
    git:
      enabled: true
      mode: simple
  endpoints:
    web:
      base-path: /